In [1]:
print("Name: Pooja Rawool")
print("PRN: 1132200081")

Name: Pooja Rawool
PRN: 1132200081


In [2]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
from sklearn.model_selection import train_test_split 
from sklearn import linear_model
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
%cd D:\MSC\Trimester2\LabonML\Datasets

D:\MSC\Trimester2\LabonML\Datasets


In [4]:
%pwd

'D:\\MSC\\Trimester2\\LabonML\\Datasets'

In [5]:
#SGDClassifier
class AnalysisUtils:
    def load_dataset(self, csvfilename, testpercent):
        dataset = pd.read_csv(csvfilename)
        dataset.info()
        x=dataset.iloc[:,0:13]
        y=dataset['target']
        
        #Train Test Split 
        x_train,x_test,y_train,y_test= train_test_split(x,y, test_size= testpercent, random_state=0)
        return x_train,x_test,y_train,y_test

In [6]:
myutils = AnalysisUtils()

In [7]:
x_trainset, x_testset,y_trainset, y_testset = myutils.load_dataset('heart.csv',0.2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [8]:
x_trainset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
74    43    0   2       122   213    0        1      165      0      0.2   
153   66    0   2       146   278    0        0      152      0      0.0   
64    58    1   2       140   211    1        0      165      0      0.0   
296   63    0   0       124   197    0        1      136      1      0.0   
287   57    1   1       154   232    0        0      164      0      0.0   

     slope  ca  thal  
74       1   0     2  
153      1   1     2  
64       2   0     2  
296      1   0     2  
287      2   1     2

In [9]:
x_trainset.shape

(242, 13)

In [10]:
y_trainset.head()

74     1
153    1
64     1
296    0
287    0
Name: target, dtype: int64

In [11]:
y_trainset.shape

(242,)

In [12]:
clf = linear_model.SGDClassifier(max_iter=100, tol=1e-9,eta0=0.01,loss='hinge')
clf.fit(x_trainset, y_trainset)

SGDClassifier(eta0=0.01, max_iter=100, tol=1e-09)

In [13]:
clf.coef_

array([[ -472.97803763,  -767.55865377,  1406.94100892,  -667.11640807,
          -20.23836294,   -23.98620793,    86.20043475,   786.29787872,
         -667.86597706, -1399.29540514,   362.04182595, -1505.13454764,
         -829.0233116 ]])

In [14]:
clf.intercept_

array([-125.85547385])

In [15]:
clf.n_iter_

51

In [16]:
y_pred = clf.predict(x_testset)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0], dtype=int64)

In [17]:
confusion_matrix(y_testset, y_pred)

array([[21,  6],
       [10, 24]], dtype=int64)

In [18]:
class AnalysisUtils:
    def load_dataset(self, jsonfilename, testpercent):
        dataset = pd.read_json(jsonfilename)
        dataset.info()
        x=dataset.iloc[:,0:4]
        y=dataset['species']
        
        #Train Test Split 
        x_train,x_test,y_train,y_test= train_test_split(x,y, test_size= testpercent, random_state=0)
        return x_train,x_test,y_train,y_test

In [19]:
myutils = AnalysisUtils()

In [20]:
x_trainset, x_testset,y_trainset, y_testset = myutils.load_dataset('iris.json',0.2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   sepalLength  150 non-null    float64
 1   sepalWidth   150 non-null    float64
 2   petalLength  150 non-null    float64
 3   petalWidth   150 non-null    float64
 4   species      150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [21]:
x_trainset.head()

sepalLength  sepalWidth  petalLength  petalWidth
137          6.4         3.1          5.5         1.8
84           5.4         3.0          4.5         1.5
27           5.2         3.5          1.5         0.2
127          6.1         3.0          4.9         1.8
132          6.4         2.8          5.6         2.2

In [22]:
x_trainset.shape

(120, 4)

In [23]:
y_trainset.head()

137     virginica
84     versicolor
27         setosa
127     virginica
132     virginica
Name: species, dtype: object

In [24]:
y_trainset.shape

(120,)

In [25]:
clf.fit(x_trainset, y_trainset)

SGDClassifier(eta0=0.01, max_iter=100, tol=1e-09)

In [26]:
clf.coef_

array([[   6.52528548,   19.03208265,  -36.43284394,  -15.22566612],
       [  29.59394357, -102.31704519,   35.09979353,  -87.4053682 ],
       [-122.06047032,  -82.1201941 ,  182.53079507,  173.19895483]])

In [27]:
clf.intercept_

array([   9.84206934,  139.01570492, -141.47899105])

In [28]:
clf.n_iter_

28

In [29]:
y_pred = clf.predict(x_testset)
y_pred

array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa'], dtype='<U10')

In [30]:
confusion_matrix(y_testset, y_pred)

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]], dtype=int64)

In [31]:
#SGDRegressor
class AnalysisUtils:
    def load_dataset(self, csvfilename, testpercent):
        dataset = pd.read_csv(csvfilename)
        dataset.info()
        x=dataset['Temperature (Xi)'].values.reshape(-1,1)
        y=dataset['Yield (Yi)'].values.reshape(-1,1)
        #Train Test Split 
        x_train,x_test,y_train,y_test= train_test_split(x,y, test_size= testpercent, random_state=0)
        return x_train,x_test,y_train,y_test

In [32]:
myutils = AnalysisUtils()

In [33]:
x_trainset, x_testset,y_trainset, y_testset = myutils.load_dataset('Yield_vs_Temperature.csv',0.2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Observation Number  25 non-null     int64
 1   Temperature (Xi)    25 non-null     int64
 2   Yield (Yi)          25 non-null     int64
dtypes: int64(3)
memory usage: 728.0 bytes


In [34]:
x_trainset.shape

(20, 1)

In [35]:
y_trainset.shape

(20, 1)

In [36]:
sgdr = linear_model.SGDRegressor(max_iter=100, tol=1e-9,eta0=0.01,loss='huber')
sgdr.fit(x_trainset,y_trainset )

D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SGDRegressor(loss='huber', max_iter=100, tol=1e-09)

In [37]:
sgdr.coef_

array([2.20878054])

In [38]:
sgdr.intercept_

array([0.03365424])

In [39]:
sgdr.n_iter_

12

In [40]:
score = sgdr.score(x_testset, y_testset)
print(score)

0.9640814268997269


In [41]:
ypred = sgdr.predict(x_testset)
print(ypred)

[130.35170581 119.30780313 198.82390239 181.15365811 163.48341383]
